name: Bodhi
favicon: null
layout_spectrum: 0.44714482477866113
typography_spectrum: 0.21370340301655233
title: 'Guide to Industry Activity Awareness '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.12214565370231867
  lightness: 0.0870032359380275
  saturation: 0.46974134468473494
  rhythmicContrast: 0.193859237479046
purpose: []
